name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main # Replace with your deployment branch name
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main # Replace with your deployment branch name

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Build and Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # This secret is automatically created by GitHub
          action: "upload"
          app_location: "/" # Location of your app source code
          api_location: "api" # Location of your API source code, if any
          output_location: "build" # Location of the built output for your app
